잡코리아 데이터 분석 채용공고 수집을 위한 코드

In [1]:
from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager
from selenium.webdriver.support.ui import WebDriverWait

from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By

from selenium.common.exceptions import NoSuchElementException
import time
import re

import requests
from bs4 import BeautifulSoup
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

# 한글 폰트 설정
plt.rc('font', family = 'AppleGothic')

In [2]:
# Selenium으로 웹 드라이버 실행
service = Service(executable_path=ChromeDriverManager().install())
driver = webdriver.Chrome(service=service)

url ='https://www.jobkorea.co.kr/'
driver.get(url)
driver.implicitly_wait(2) # 응답 바로 읽지 않고 기다려주기

# 팝업 닫기 시도
try:
    popup = driver.find_element(By.CLASS_NAME, 'Modal_overlay__1qbupvq0')
    close_btn = popup.find_element(By.XPATH, './/button/i')
    close_btn.click()
    time.sleep(1)
    print("팝업 닫음")

except NoSuchElementException:
    print("팝업 없음, 바로 진행")
    
# search_input = driver.find_element(By.CLASS_NAME, 'Modal_overlay__1qbupvq0')
# search_input1 = search_input.find_element(By.XPATH, '//*[@id="jk-_r_0_"]/button/i')
# search_input1.click()
# time.sleep(2)

# 검색어 입력
search_input = driver.find_element(By.ID, 'radix-_R_kl6anmlbH2_')
search_input.send_keys('데이터 분석') 
time.sleep(2)

# 검색 버튼 클릭
search_click = driver.find_element(By.XPATH, '/html/body/div[3]/div[1]/div/div/div[1]/div[1]/div/div[2]/div/div/div/div[1]/div[2]/button[2]')
search_click.click()
time.sleep(2)

# 전체 내용
search = driver.find_element(By.CSS_SELECTOR, "#jk-_R_olfaknqdb_-content-recruit > div > div:nth-child(2) > div.Flex_display_flex__i0l0hl2.Flex_gap_space16__i0l0hlj.Flex_direction_column__i0l0hl4")
search_info = search.find_elements(By.CLASS_NAME, 'Box_bgColor_white__1wwr54u0.Box_borderColor_default__1wwr54u5.Box_borderSize_1__1wwr54ud.styles_p_space0__dk46ts61.styles_radius_radius16__dk46ts9d.Shadow_root_list__bm2zcc6.dlua7o0')

recruit = []
url = []
company = []
detail_list = []

for i in range(len(search_info)):
    title_link = search_info[i].find_element(By.CLASS_NAME, 'styles_mb_space2__dk46ts4t') # 제목과 링크
    title = title_link.text # 제목
    link = title_link.find_element(By.TAG_NAME, 'a').get_attribute('href') # 링크
    cop_nm = search_info[i].find_element(By.CLASS_NAME, 'Typography_variant_size16__344nw26.Typography_weight_regular__344nw2e.Typography_color_gray700__344nw2o.Typography_truncate__344nw2y').text # 회사명
    detail = search_info[i].find_element(By.CLASS_NAME, 'Flex_display_flex__i0l0hl2.Flex_gap_space10__i0l0hlm.Flex_direction_column__i0l0hl4').text.split('\n')
    detail_final = [x for x in detail if re.search(r"[가-힣a-zA-Z0-9]", x)] # 특수문자만 있을 경우 제외
    

    recruit.append(title) # 제목
    url.append(link)
    company.append(cop_nm)
    detail_list.append(detail_final)

df_jobkorea = pd.DataFrame({'Site':'Job_Korea', 'Col_company':company, 'Col_recruit':recruit, 'Col_detail':detail_list, 'Col_url':url})

driver.quit()

display(df_jobkorea.head())
display(df_jobkorea.tail())

팝업 닫음

,Site,Col_company,Col_recruit,Col_detail,Col_url
0,Job_Korea,핫셀러,데이터 분석을 통해 앱 서비스를 성공시킬 기획자 채용,"[서울 동대문구, 솔루션·SI·CRM·ERP, 웹기획, PL·PM·PO, AI기획자...",https://www.jobkorea.co.kr/Recruit/GI_Read/486...
1,Job_Korea,㈜그라비티,[그라비티] 데이터 분석 인원 경력 채용,"[서울 마포구, 게임·애니메이션, DBA, 데이터사이언티스트, 데이터분석가, 즉시 ...",https://www.jobkorea.co.kr/Recruit/GI_Read/485...
2,Job_Korea,피엠인터내셔널코리아(유),시니어 AI 및 데이터 분석 전문가,"[서울 영등포구, 무역·상사, 데이터분석가, 즉시 지원, 경력5년↑, 유연근무, 생...",https://www.jobkorea.co.kr/Recruit/GI_Read/485...
3,Job_Korea,메가존클라우드㈜,보안 데이터 분석 엔지니어 채용 (SIEM/SOAR/Senior),"[경기 과천시, 솔루션·SI·CRM·ERP, 데이터엔지니어, 데이터사이언티스트, 보...",https://www.jobkorea.co.kr/Recruit/GI_Read/486...
4,Job_Korea,㈜딥마인,"데이터 분석, 수요 예측 분석 채용","[서울 영등포구 외 3, 솔루션·SI·CRM·ERP, AI/ML엔지니어, 연봉 3,...",https://www.jobkorea.co.kr/Recruit/GI_Read/484...

,Site,Col_company,Col_recruit,Col_detail,Col_url
15,Job_Korea,㈜큐로드,[수원] 데이터 분석 담당자 채용,"[경기 수원시, 게임·애니메이션, 웹기획, 사무담당자, 데이터사이언티스트, 즉시 지...",https://www.jobkorea.co.kr/Recruit/GI_Read/486...
16,Job_Korea,㈜스르르,[온라인MD] NUVN에서 성과/데이터 분석형 MD 채용합니다,"[서울 마포구, 생활용품·소비재·기타, 마케팅기획, 퍼포먼스마케터, MD, 즉시 지...",https://www.jobkorea.co.kr/Recruit/GI_Read/486...
17,Job_Korea,네이버파이낸셜,[네이버페이] 알림 데이터 분석 및 운영 (계약직),"[경기 성남시, 은행·금융, 데이터엔지니어, 데이터사이언티스트, 홈페이지 지원, 경...",https://www.jobkorea.co.kr/Recruit/GI_Read/486...
18,Job_Korea,㈜어크로스비,ERP·WMS 데이터 분석 단기 아르바이트(2개월),"[서울 강남구, 물류·운송·배송, 경영·비즈니스기획, 물류관리자, 시급 11,000...",https://www.jobkorea.co.kr/Recruit/GI_Read/486...
19,Job_Korea,㈜엑셀리언트,"(삼성동) 데이터 분석, 컨설팅 모집 (경력)","[서울 강남구, IT컨설팅, 웹기획, 마케팅기획, 설문·리서치, 즉시 지원, 경력,...",https://www.jobkorea.co.kr/Recruit/GI_Read/486...

In [3]:
# 잡코리아 데이터 저장
df_jobkorea.to_csv('data_tmp/df_jobkorea.csv', index=False, encoding='utf-8-sig')